/**
 * Fetches open-data lists of free / disposable email domains and emits a
 * TypeScript module the runtime imports. Run this before `bun run build`.
 *
 * Sources (both MIT / CC0 / public-domain compatible):
 *   - free:       willwhite/freemail
 *   - disposable: disposable-email-domains/disposable-email-domains
 */

const SOURCES = {
    free:       'https://raw.githubusercontent.com/willwhite/freemail/master/data/free.txt',
    disposable: 'https://raw.githubusercontent.com/disposable-email-domains/disposable-email-domains/main/disposable_email_blocklist.conf',
} as const;

const OUTPUT_PATH = new URL('../src/data/consumer-domains.ts', import.meta.url);

async function fetchDomains(url: string): Promise<string[]> {
    const res = await fetch(url);
    if (!res.ok) throw new Error(`Fetch failed ${res.status} for ${url}`);
    const text = await res.text();
    return text
        .split('\n')
        .map(line => line.trim().toLowerCase())
        .filter(line => line && !line.startsWith('#'))
        .filter(line => /^[a-z0-9.-]+\.[a-z]{2,}$/.test(line));
}

function renderSet(name: string, items: string[]): string {
    // Sorted, deduped, one per line — keeps diffs small when the lists change.
    const unique = [...new Set(items)].sort();
    const literals = unique.map(d => `    ${JSON.stringify(d)},`).join('\n');
    return `export const ${name}: ReadonlySet<string> = new Set<string>([\n${literals}\n]);`;
}

const stamp = new Date().toISOString();
console.log('Fetching consumer-domain datasets…');

const [free, disposable] = await Promise.all([
    fetchDomains(SOURCES.free),
    fetchDomains(SOURCES.disposable),
]);

console.log(`  free:       ${free.length} domains`);
console.log(`  disposable: ${disposable.length} domains`);

const body = `// AUTO-GENERATED by scripts/build-data.ts at ${stamp}
// Sources:
//   free:       ${SOURCES.free}
//   disposable: ${SOURCES.disposable}
// Do not edit by hand — re-run \`bun run datasets\`.

${renderSet('FREE_DOMAINS', free)}

${renderSet('DISPOSABLE_DOMAINS', disposable)}

export const DATASET_VERSION = ${JSON.stringify(stamp)};
`;

await Bun.write(OUTPUT_PATH, body);
console.log(`Wrote ${OUTPUT_PATH.pathname}`);
