import type { Provider, ProviderCategory } from './types.ts';

// Each provider lists MX hostname suffixes that uniquely identify it.
// Matching is done by exact-host or dot-suffix match in identify.ts —
// so "mail.com" will not match "googlemail.com". Longest matcher wins,
// so a specific entry like "mail.protection.outlook.com" beats a broad
// one like "outlook.com" when both apply.
//
// Categories:
//   mailbox   – primary mailbox hosting (Google Workspace, M365, Zoho…)
//   consumer  – consumer mail service (Yahoo, AOL, iCloud, ISP webmail…)
//   gateway   – security / spam-filter sitting IN FRONT of a mailbox
//   forwarder – forwards mail to another address
//   relay     – transactional inbound API service (no human mailbox)

export const PROVIDERS: readonly Provider[] = [
    // ---- Business mailbox hosting ------------------------------------------
    { name: 'Google Workspace',     category: 'mailbox', url: 'https://workspace.google.com',  matchers: ['aspmx.l.google.com', 'googlemail.com', 'google.com'] },
    { name: 'Microsoft 365',        category: 'mailbox', url: 'https://www.microsoft.com/microsoft-365', matchers: ['mail.protection.outlook.com', 'outlook.com', 'office365.com'] },
    { name: 'Zoho Mail',            category: 'mailbox', url: 'https://www.zoho.com/mail/',    matchers: ['zoho.com', 'zohomail.com', 'zohomail.eu', 'zohomail.in'] },
    { name: 'Fastmail',             category: 'mailbox', url: 'https://www.fastmail.com',      matchers: ['messagingengine.com', 'fastmail.com'] },
    { name: 'Proton Mail',          category: 'mailbox', url: 'https://proton.me/mail',        matchers: ['mail.protonmail.ch', 'mailsec.protonmail.ch', 'protonmail.ch', 'protonmail.com', 'proton.me'] },
    { name: 'Tuta (Tutanota)',      category: 'mailbox', url: 'https://tuta.com',              matchers: ['tutanota.de', 'tutao.de', 'tuta.io'] },
    { name: 'HEY',                  category: 'mailbox', url: 'https://hey.com',               matchers: ['hey.com'] },
    { name: 'Migadu',               category: 'mailbox', url: 'https://www.migadu.com',        matchers: ['migadu.com'] },
    { name: 'Purelymail',           category: 'mailbox', url: 'https://purelymail.com',        matchers: ['purelymail.com'] },
    { name: 'Mailbox.org',          category: 'mailbox', url: 'https://mailbox.org',           matchers: ['mailbox.org'] },
    { name: 'Posteo',               category: 'mailbox', url: 'https://posteo.de',             matchers: ['posteo.de'] },
    { name: 'Mailfence',            category: 'mailbox', url: 'https://mailfence.com',         matchers: ['mailfence.com'] },
    { name: 'Runbox',               category: 'mailbox', url: 'https://runbox.com',            matchers: ['runbox.com'] },
    { name: 'Hushmail',             category: 'mailbox', url: 'https://www.hushmail.com',      matchers: ['hushmail.com'] },
    { name: 'StartMail',            category: 'mailbox', url: 'https://www.startmail.com',     matchers: ['startmail.com'] },
    { name: 'CounterMail',          category: 'mailbox', url: 'https://countermail.com',       matchers: ['countermail.com'] },
    { name: 'Disroot',              category: 'mailbox', url: 'https://disroot.org',           matchers: ['disroot.org'] },
    { name: 'Soverin',              category: 'mailbox', url: 'https://soverin.net',           matchers: ['soverin.net'] },
    { name: 'MXroute',              category: 'mailbox', url: 'https://mxroute.com',           matchers: ['mxroute.com', 'mxlogin.com'] },
    { name: 'Rackspace Email',      category: 'mailbox', url: 'https://www.rackspace.com/email-hosting', matchers: ['emailsrvr.com'] },
    { name: 'GoDaddy (legacy)',     category: 'mailbox', url: 'https://www.godaddy.com',       matchers: ['secureserver.net'] },
    { name: 'IONOS / 1&1',          category: 'mailbox', url: 'https://www.ionos.com',         matchers: ['ionos.com', 'ionos.de', 'kundenserver.de', 'schlund.de', '1and1.com'] },
    { name: 'Strato',               category: 'mailbox', url: 'https://www.strato.de',         matchers: ['strato.de'] },
    { name: 'Hostinger',            category: 'mailbox', url: 'https://www.hostinger.com',     matchers: ['hostinger.com'] },
    { name: 'OVH',                  category: 'mailbox', url: 'https://www.ovh.com',           matchers: ['ovh.net', 'mail.ovh.net'] },
    { name: 'Gandi Mail',           category: 'mailbox', url: 'https://www.gandi.net/en/domain/email', matchers: ['mail.gandi.net', 'gandi.net'] },
    { name: 'Namecheap Private Email', category: 'mailbox', url: 'https://www.namecheap.com/hosting/email/', matchers: ['privateemail.com', 'jellyfish.systems'] },
    { name: 'DreamHost Mail',       category: 'mailbox', url: 'https://www.dreamhost.com',     matchers: ['dreamhost.com'] },
    { name: 'Bluehost',             category: 'mailbox', url: 'https://www.bluehost.com',      matchers: ['bluehost.com'] },
    { name: 'SiteGround',           category: 'mailbox', url: 'https://www.siteground.com',    matchers: ['siteground.biz'] },
    { name: 'Tucows OpenSRS (Hover, OnlyDomains, Rebel)', category: 'mailbox', url: 'https://opensrs.com', matchers: ['hostedemail.com'] },
    { name: 'One.com',              category: 'mailbox', url: 'https://www.one.com',           matchers: ['one.com'] },
    { name: 'TransIP',              category: 'mailbox', url: 'https://www.transip.eu',        matchers: ['transip.email', 'transip.nl'] },
    { name: 'A2 Hosting',           category: 'mailbox', url: 'https://www.a2hosting.com',     matchers: ['a2hosting.com'] },
    { name: 'Hosteurope',           category: 'mailbox', url: 'https://www.hosteurope.de',     matchers: ['hosteurope.de'] },
    { name: 'Manitu',               category: 'mailbox', url: 'https://www.manitu.de',         matchers: ['manitu.de'] },
    { name: 'All-Inkl',             category: 'mailbox', url: 'https://all-inkl.com',          matchers: ['all-inkl.com'] },
    { name: 'Pair Networks',        category: 'mailbox', url: 'https://www.pair.com',          matchers: ['pair.com'] },
    { name: 'Hostpapa',             category: 'mailbox', url: 'https://www.hostpapa.com',      matchers: ['hostpapa.com'] },
    { name: 'Atmail Cloud',         category: 'mailbox', url: 'https://www.atmail.com',        matchers: ['atmail.com'] },
    { name: 'Riseup',               category: 'mailbox', url: 'https://riseup.net',            matchers: ['riseup.net'] },
    { name: 'Cock.li',              category: 'mailbox', url: 'https://cock.li',               matchers: ['cock.li'] },
    { name: 'Eclipso',              category: 'mailbox', url: 'https://www.eclipso.de',        matchers: ['eclipso.de'] },
    { name: 'Microsoft 365 Germany',category: 'mailbox', url: 'https://www.microsoft.com/microsoft-365', matchers: ['mail.protection.outlook.de'] },
    { name: 'Microsoft 365 US Gov', category: 'mailbox', url: 'https://www.microsoft.com/en-us/microsoft-365/government', matchers: ['mail.protection.office365.us'] },
    { name: 'Beget',                category: 'mailbox', url: 'https://beget.com',             matchers: ['beget.com'] },
    { name: 'Timeweb',              category: 'mailbox', url: 'https://timeweb.com',           matchers: ['timeweb.ru'] },
    { name: 'Reg.ru',               category: 'mailbox', url: 'https://www.reg.ru',            matchers: ['reg.ru'] },
    { name: 'Freeola',              category: 'mailbox', url: 'https://www.freeola.com',       matchers: ['freeola.com'] },
    { name: 'Mailcore',             category: 'mailbox', url: 'https://mailcore.io',           matchers: ['mailcore.email', 'mailcore.io'] },
    { name: 'NameBright Mail',      category: 'mailbox', url: 'https://www.namebright.com',    matchers: ['namebrightmail.com'] },

    // ---- Consumer mailbox services ----------------------------------------
    { name: 'Yahoo Mail',           category: 'consumer', url: 'https://mail.yahoo.com',       matchers: ['yahoodns.net'] },
    { name: 'AOL Mail',             category: 'consumer', url: 'https://mail.aol.com',         matchers: ['mx.aol.com', 'aol.com'] },
    { name: 'Apple iCloud Mail',    category: 'consumer', url: 'https://www.icloud.com/mail',  matchers: ['mail.icloud.com', 'icloud.com', 'me.com'] },
    { name: 'Mail.com',             category: 'consumer', url: 'https://www.mail.com',         matchers: ['mail.com'] },
    { name: 'GMX',                  category: 'consumer', url: 'https://www.gmx.com',          matchers: ['gmx.net', 'gmx.com'] },
    { name: 'Yandex Mail',          category: 'consumer', url: 'https://mail.yandex.com',      matchers: ['yandex.net', 'yandex.ru', 'mx.yandex.net'] },
    { name: 'Mail.ru',              category: 'consumer', url: 'https://mail.ru',              matchers: ['mxs.mail.ru', 'mail.ru'] },
    { name: 'Web.de',               category: 'consumer', url: 'https://web.de',               matchers: ['web.de'] },
    { name: 'T-Online',             category: 'consumer', url: 'https://www.t-online.de',      matchers: ['t-online.de'] },
    { name: 'Freenet',              category: 'consumer', url: 'https://www.freenet.de',       matchers: ['freenet.de'] },
    { name: 'NetEase 163',          category: 'consumer', url: 'https://mail.163.com',         matchers: ['mxmail.netease.com', 'netease.com', '163.com', 'qiye.163.com'] },
    { name: 'NetEase 126',          category: 'consumer', url: 'https://mail.126.com',         matchers: ['126.com'] },
    { name: 'QQ Mail',              category: 'consumer', url: 'https://mail.qq.com',          matchers: ['qq.com', 'mail.qq.com'] },
    { name: 'Sina Mail',            category: 'consumer', url: 'https://mail.sina.com.cn',     matchers: ['sinamail.sina.com.cn', 'sina.com'] },
    { name: 'Naver Mail',           category: 'consumer', url: 'https://mail.naver.com',       matchers: ['mx1.naver.com', 'mx2.naver.com', 'mx3.naver.com', 'naver.com'] },
    { name: 'Daum (Hanmail)',       category: 'consumer', url: 'https://mail.daum.net',        matchers: ['mx.daum.net', 'daum.net'] },
    { name: 'BT Internet',          category: 'consumer', url: 'https://www.bt.com/email',     matchers: ['btinternet.com', 'bt.com'] },
    { name: 'Sky',                  category: 'consumer', url: 'https://www.sky.com',          matchers: ['sky.com'] },
    { name: 'Telstra Bigpond',      category: 'consumer', url: 'https://www.telstra.com.au',   matchers: ['bigpond.com'] },
    { name: 'Orange.fr',            category: 'consumer', url: 'https://mail.orange.fr',       matchers: ['orange.fr'] },
    { name: 'SFR',                  category: 'consumer', url: 'https://www.sfr.fr',           matchers: ['sfr.fr'] },
    { name: 'Comcast Xfinity',      category: 'consumer', url: 'https://www.xfinity.com',      matchers: ['comcast.net'] },
    { name: 'Cox Communications',   category: 'consumer', url: 'https://www.cox.com',          matchers: ['cox.net'] },
    { name: 'Charter Spectrum',     category: 'consumer', url: 'https://www.spectrum.com',     matchers: ['charter.net'] },
    { name: 'Optimum (Altice)',     category: 'consumer', url: 'https://www.optimum.com',      matchers: ['optimum.net'] },
    { name: 'Frontier',             category: 'consumer', url: 'https://frontier.com',         matchers: ['frontiernet.net', 'frontier.com'] },
    { name: 'CenturyLink',          category: 'consumer', url: 'https://www.centurylink.com',  matchers: ['centurylink.net'] },
    { name: 'EarthLink',            category: 'consumer', url: 'https://www.earthlink.net',    matchers: ['earthlink.net'] },
    { name: 'NetZero',              category: 'consumer', url: 'https://www.netzero.net',      matchers: ['netzero.net'] },
    { name: 'Juno',                 category: 'consumer', url: 'https://www.juno.com',         matchers: ['juno.com'] },
    { name: 'Bell Canada / Sympatico', category: 'consumer', url: 'https://www.bell.ca',       matchers: ['bellnet.ca', 'sympatico.ca'] },
    { name: 'Rogers',               category: 'consumer', url: 'https://www.rogers.com',       matchers: ['rogers.com'] },
    { name: 'Telus',                category: 'consumer', url: 'https://www.telus.com',        matchers: ['telus.net'] },
    { name: 'Shaw',                 category: 'consumer', url: 'https://www.shaw.ca',          matchers: ['shaw.ca'] },
    { name: 'TalkTalk',             category: 'consumer', url: 'https://www.talktalk.co.uk',   matchers: ['talktalk.net'] },
    { name: 'Laposte.net',          category: 'consumer', url: 'https://laposte.net',          matchers: ['laposte.net'] },
    { name: 'Free.fr',              category: 'consumer', url: 'https://www.free.fr',          matchers: ['free.fr', 'freebox.fr'] },
    { name: 'Libero',               category: 'consumer', url: 'https://www.libero.it',        matchers: ['libero.it'] },
    { name: 'Virgilio',             category: 'consumer', url: 'https://www.virgilio.it',      matchers: ['virgilio.it'] },
    { name: 'Tiscali',              category: 'consumer', url: 'https://www.tiscali.it',       matchers: ['tiscali.it'] },
    { name: 'TIN / Alice',          category: 'consumer', url: 'https://www.tim.it',           matchers: ['tin.it', 'alice.it'] },
    { name: 'Vodafone',             category: 'consumer', url: 'https://www.vodafone.com',     matchers: ['vodafone.de', 'vodafone.com'] },
    { name: 'O2',                   category: 'consumer', url: 'https://www.o2online.de',      matchers: ['o2online.de', 'o2.co.uk'] },
    { name: 'Rediffmail',           category: 'consumer', url: 'https://www.rediff.com',       matchers: ['rediffmail.com', 'rediffmailpro.com'] },
    { name: 'Walla',                category: 'consumer', url: 'https://www.walla.co.il',      matchers: ['walla.co.il'] },
    { name: 'Nate',                 category: 'consumer', url: 'https://www.nate.com',         matchers: ['nate.com'] },
    { name: 'Yeah.net',             category: 'consumer', url: 'https://mail.yeah.net',        matchers: ['yeah.net'] },
    { name: 'Sohu',                 category: 'consumer', url: 'https://mail.sohu.com',        matchers: ['sohu.com'] },
    { name: 'Tom.com',              category: 'consumer', url: 'https://www.tom.com',          matchers: ['tom.com'] },
    { name: 'Optus',                category: 'consumer', url: 'https://www.optus.com.au',     matchers: ['optusnet.com.au'] },
    { name: 'iiNet',                category: 'consumer', url: 'https://www.iinet.net.au',     matchers: ['iinet.net.au'] },

    // ---- Disposable / temporary mailbox services --------------------------
    { name: 'Mailinator',           category: 'consumer', url: 'https://www.mailinator.com',   matchers: ['mailinator.com'] },
    { name: 'YOPmail',              category: 'consumer', url: 'https://yopmail.com',          matchers: ['yopmail.com'] },
    { name: 'Mail.tm',              category: 'consumer', url: 'https://mail.tm',              matchers: ['mail.tm'] },
    { name: 'Generator.email',      category: 'consumer', url: 'https://generator.email',      matchers: ['generator.email'] },
    { name: 'Dropmail.me',          category: 'consumer', url: 'https://dropmail.me',          matchers: ['dropmail.me'] },
    { name: 'Discard.email',        category: 'consumer', url: 'https://discard.email',        matchers: ['discard.email'] },
    { name: '10mail',               category: 'consumer', url: 'https://10mail.org',           matchers: ['10mail.org', '10mail.xyz'] },
    { name: 'TempM',                category: 'consumer', url: 'https://tempm.com',            matchers: ['tempm.com'] },
    { name: 'EmailFake',            category: 'consumer', url: 'https://emailfake.com',        matchers: ['emailfake.com'] },

    // ---- Security gateways -------------------------------------------------
    { name: 'Proofpoint',           category: 'gateway', url: 'https://www.proofpoint.com',    matchers: ['pphosted.com', 'ppe-hosted.com'] },
    { name: 'Mimecast',             category: 'gateway', url: 'https://www.mimecast.com',      matchers: ['mimecast.com', 'mimecast.co.za', 'mimecast.com.au'] },
    { name: 'Cisco Secure Email',   category: 'gateway', url: 'https://www.cisco.com/c/en/us/products/security/email-security', matchers: ['iphmx.com'] },
    { name: 'Barracuda Email Protection', category: 'gateway', url: 'https://www.barracuda.com', matchers: ['barracudanetworks.com'] },
    { name: 'Trend Micro Email Security', category: 'gateway', url: 'https://www.trendmicro.com/en_us/business/products/user-protection/sps/email-and-collaboration.html', matchers: ['tmes.trendmicro.com', 'tmes.trendmicro.eu'] },
    { name: 'Sophos Email',         category: 'gateway', url: 'https://www.sophos.com/en-us/products/sophos-email', matchers: ['reflexion.net', 'sophos.com'] },
    { name: 'Forcepoint',           category: 'gateway', url: 'https://www.forcepoint.com',    matchers: ['mailcontrol.com'] },
    { name: 'Symantec MessageLabs', category: 'gateway', url: 'https://www.broadcom.com/products/cybersecurity/email', matchers: ['messagelabs.com'] },
    { name: 'Vade Secure',          category: 'gateway', url: 'https://www.vadesecure.com',    matchers: ['vadesecure.com'] },
    { name: 'MailRoute',            category: 'gateway', url: 'https://www.mailroute.net',     matchers: ['mailroute.net'] },
    { name: 'AppRiver / Zix',       category: 'gateway', url: 'https://www.appriver.com',      matchers: ['appriver.com'] },
    { name: 'FireEye / Trellix',    category: 'gateway', url: 'https://www.trellix.com',       matchers: ['fireeyecloud.com'] },
    { name: 'Hornetsecurity',       category: 'gateway', url: 'https://www.hornetsecurity.com',matchers: ['hornetsecurity.com', 'antispameurope.com'] },
    { name: 'N-able Mail Assure',   category: 'gateway', url: 'https://www.n-able.com/products/mail-assure', matchers: ['mailprotect.be', 'spamexperts.com'] },
    { name: 'Retarus',              category: 'gateway', url: 'https://www.retarus.com',       matchers: ['retarus.com'] },
    { name: 'VIPRE Email Security (FuseMail)', category: 'gateway', url: 'https://vipre.com',  matchers: ['antispamcloud.com', 'fusemail.com'] },
    { name: 'SpamTitan',            category: 'gateway', url: 'https://www.spamtitan.com',     matchers: ['spamtitancloud.com', 'spamtitan.com'] },
    { name: 'Halon',                category: 'gateway', url: 'https://halon.io',              matchers: ['halon.io'] },
    { name: 'EveryCloud',           category: 'gateway', url: 'https://www.everycloudtech.com',matchers: ['everycloudtech.com'] },
    { name: 'SpamHero',             category: 'gateway', url: 'https://www.spamhero.com',      matchers: ['spamhero.com'] },
    { name: 'MailChannels',         category: 'gateway', url: 'https://www.mailchannels.com',  matchers: ['mailchannels.net'] },
    { name: 'Intermedia',           category: 'gateway', url: 'https://www.intermedia.com',    matchers: ['intermedia.net'] },
    { name: 'MailSpamProtection (SiteGround)', category: 'gateway', url: 'https://www.siteground.com', matchers: ['mailspamprotection.com'] },

    // ---- Forwarders --------------------------------------------------------
    { name: 'Cloudflare Email Routing', category: 'forwarder', url: 'https://www.cloudflare.com/products/email-routing/', matchers: ['mx.cloudflare.net'] },
    { name: 'SimpleLogin',          category: 'forwarder', url: 'https://simplelogin.io',      matchers: ['simplelogin.co'] },
    { name: 'addy.io',              category: 'forwarder', url: 'https://addy.io',             matchers: ['addy.io', 'anonaddy.me'] },
    { name: 'ForwardEmail.net',     category: 'forwarder', url: 'https://forwardemail.net',    matchers: ['forwardemail.net'] },
    { name: 'Pobox',                category: 'forwarder', url: 'https://www.pobox.com',       matchers: ['pobox.com'] },
    { name: '33Mail',               category: 'forwarder', url: 'https://33mail.com',          matchers: ['33mail.com'] },
    { name: 'Burner Mail',          category: 'forwarder', url: 'https://burnermail.io',       matchers: ['burnermail.io'] },
    { name: 'ImprovMX',             category: 'forwarder', url: 'https://improvmx.com',        matchers: ['improvmx.com'] },
    { name: 'Namecheap Email Forwarding', category: 'forwarder', url: 'https://www.namecheap.com/domains/freedns/', matchers: ['registrar-servers.com'] },
    { name: 'Spaceship Email Forwarding', category: 'forwarder', url: 'https://www.spaceship.com', matchers: ['spaceship.net', 'efwd.spaceship.net'] },
    { name: 'SpamGourmet',          category: 'forwarder', url: 'https://www.spamgourmet.com', matchers: ['spamgourmet.com'] },

    // ---- Inbound relays (transactional) -----------------------------------
    { name: 'Amazon SES',           category: 'relay', url: 'https://aws.amazon.com/ses/',     matchers: ['amazonaws.com'] },
    { name: 'Postmark',             category: 'relay', url: 'https://postmarkapp.com',         matchers: ['mtasv.net', 'postmarkapp.com'] },
    { name: 'Mailgun',              category: 'relay', url: 'https://www.mailgun.com',         matchers: ['mailgun.org'] },
    { name: 'SendGrid',             category: 'relay', url: 'https://sendgrid.com',            matchers: ['sendgrid.net'] },
    { name: 'Mailchimp Transactional', category: 'relay', url: 'https://mailchimp.com/developer/transactional/', matchers: ['mandrillapp.com'] },
    { name: 'SparkPost',            category: 'relay', url: 'https://www.sparkpost.com',       matchers: ['sparkpostmail.com'] },
    { name: 'Brevo (Sendinblue)',   category: 'relay', url: 'https://www.brevo.com',           matchers: ['brevo.com', 'sendinblue.com'] },
    { name: 'Mailjet',              category: 'relay', url: 'https://www.mailjet.com',         matchers: ['mailjet.com'] },
    { name: 'SocketLabs',           category: 'relay', url: 'https://www.socketlabs.com',      matchers: ['socketlabs.com'] },
    { name: 'Elastic Email',        category: 'relay', url: 'https://elasticemail.com',        matchers: ['elasticemail.com'] },
    { name: 'Pepipost / Netcore',   category: 'relay', url: 'https://netcorecloud.com',        matchers: ['pepipost.com', 'netcorecloud.com'] },
    { name: 'MailPace',             category: 'relay', url: 'https://mailpace.com',            matchers: ['mailpace.com'] },
    { name: 'Resend',               category: 'relay', url: 'https://resend.com',              matchers: ['resend.com'] },

    // ---- Domain parking / aftermarket (MX records exist but mail isn't delivered) -----
    { name: 'Above.com Parking',    category: 'parking', url: 'https://above.com',             matchers: ['park-mx.above.com', 'above.com'] },
    { name: 'Aftermarket.pl Parking', category: 'parking', url: 'https://www.aftermarket.pl',  matchers: ['blackhole.aftermarket.pl', 'aftermarket.pl'] },
    { name: 'Key-Systems / KV Parking', category: 'parking', url: 'https://www.key-systems.net', matchers: ['kv.de'] },
];

export const CATEGORY_LABEL: Record<ProviderCategory, string> = {
    mailbox:   'Mailbox provider',
    consumer:  'Consumer service',
    gateway:   'Security gateway',
    forwarder: 'Forwarder',
    relay:     'Inbound relay',
    parking:   'Domain parking',
};

export const CATEGORY_NOTE: Partial<Record<ProviderCategory, string>> = {
    gateway:   'A security gateway filters mail before it reaches the real mailbox provider. The mailbox itself is not visible from MX records alone.',
    forwarder: 'A forwarder receives mail and re-sends it to another address. The final mailbox is not visible from MX records alone.',
    relay:     'An inbound relay accepts mail via SMTP and hands it to an application via API or webhook, not to a human mailbox.',
    parking:   "This domain's MX records point at a parking / aftermarket service. Mail sent here is most likely silently discarded — the domain isn't really receiving email.",
};
